//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameMain_LuaFacadeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameMain.LuaFacade), typeof(System.Object));
		L.RegFunction("SayHi", SayHi);
		L.RegFunction("New", _CreateGameMain_LuaFacade);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateGameMain_LuaFacade(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				GameMain.LuaFacade obj = new GameMain.LuaFacade();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: GameMain.LuaFacade.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SayHi(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			GameMain.LuaFacade.SayHi();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

